export const pimmenu = page.locator('.oxd-main-menu-item');
export const addempTab = page.locator('.oxd-topbar-body-nav-tab');
export const addEmpFirstName = page.locator('.orangehrm-firstname');
export const addEmpMidName = page.locator('.orangehrm-middlename');
export const addEmpLastName = page.locator('.orangehrm-lastname');
export const addEmpID = page.locator('.oxd-input');
export const addEmpbuttonSave = page.locator('//button[@type="submit"]');
export const addEmpNationalityField = page.locator('.oxd-select-text.oxd-select-text--active');
export const addEmpMaritalStatusField = page.locator('.oxd-select-text.oxd-select-text--active');
export const addEmpInfoSave = page.locator('//button[@type="submit"]');
export const successfullyMsg = page.getByText('SuccessSuccessfully Saved×');
export const listEmpNavTab = page.locator('.oxd-topbar-body-nav-tab');
export const listEmployeeName = page.locator('.oxd-autocomplete-text-input');
export const listEmployeeNameSelect = page.locator('oxd-autocomplete-dropdown');
export const listEmpSearchbtn = page.locator('//button[@type="submit"]');
export const editEmplistbtn = page.locator('.oxd-icon-button');
export const emplistdisplayTable = page.locator('.oxd-table.orangehrm-employee-list');
export const buttonEmpInfo = page.locator(".oxd-button");